version: "3.4"
services:
  api:
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: ./docker/api/Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    container_name: api
    env_file: ./api/.env
  cron:
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: ./docker/cron/Dockerfile
    container_name: cron
    env_file: ./api/.env
  postgres:
    image: postgres:13.2
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  ui:
    build: 
      context: ./ui
      dockerfile: ./docker/Dockerfile
    container_name: ui
    env_file: ./ui/.env
    expose:
      - 8080
    ports:
      - 8080:8080
volumes:
  pg_data:
